version: "3"
services:
    web:
        container_name: appmongo
        restart: always
        build: .
        ports:
            - '5000:3000'
        links:
            - mongo
        volumes:
            - .:/usr/src/app
    mongo:
        container_name: mongoadatabase
        image: mongo
        ports:
            - '27018:27017'
        logging:
            driver: none

